# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3835fa9d7b47c490fe07bf605374b97f44896fe563281daab8e32a52f0d8c2fea18116023df4b19c1f8c2711c290ed8884473079d23f1db8750a5d958775b731

test:
  secret_key_base: 2736176fb88e9b8731402ed8a8b9c69c740fc6d0c915a50bdff842e06a681238284497b68a61bc9753869771429710462c1bac29d933d8b53887e762e192df44

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
